// Custom environment variable declarations that augment the auto-generated Cloudflare.Env.
// (worker-configuration.d.ts is auto-generated by `wrangler types` and should not be edited.)

declare namespace Cloudflare {
  interface Env {
    // AI Gateway mode: when CF_AI_GATEWAY is set, all model requests are routed through
    // Cloudflare AI Gateway with server-managed keys. Users don't need to provide their own
    // API keys.
    CF_AI_GATEWAY?: string;            // Gateway name (enables gateway mode)
    CF_AI_GATEWAY_PROVIDERS?: string;   // Comma-separated list: "anthropic,openai,google,cloudflare"
    CF_AI_GATEWAY_ACCOUNT_ID?: string;  // Cloudflare account ID (for constructing gateway URLs)
    CF_AI_GATEWAY_API_TOKEN?: string;   // Cloudflare API token (used for non-Cloudflare providers)
    CF_AI_GATEWAY_WAI?: string;         // Alternate gateway name for Workers AI (optional)

    // Blueprint storage bindings.
    BLUEPRINTS: KVNamespace;             // Workers KV for blueprint metadata lookup
    BLUEPRINT_CONTENT: R2Bucket;         // R2 bucket for blueprint code snapshots
  }
}
