/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScheduledRouteImport } from './routes/scheduled'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OutputsRouteImport } from './routes/outputs'
import { Route as GatekeepersRouteImport } from './routes/gatekeepers'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ContextRouteImport } from './routes/context'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GatekeepersAppIdRouteImport } from './routes/gatekeepers_.$appId'
import { Route as GadgetIdRouteImport } from './routes/gadget.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as BlueprintIdRouteImport } from './routes/blueprint.$id'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsRoute = OutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersRoute = GatekeepersRouteImport.update({
  id: '/gatekeepers',
  path: '/gatekeepers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersAppIdRoute = GatekeepersAppIdRouteImport.update({
  id: '/gatekeepers_/$appId',
  path: '/gatekeepers/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const GadgetIdRoute = GadgetIdRouteImport.update({
  id: '/gadget/$id',
  path: '/gadget/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintIdRoute = BlueprintIdRouteImport.update({
  id: '/blueprint/$id',
  path: '/blueprint/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/scheduled': typeof ScheduledRoute
  '/signup': typeof SignupRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/scheduled': typeof ScheduledRoute
  '/signup': typeof SignupRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers/$appId': typeof GatekeepersAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blueprints': typeof BlueprintsRoute
  '/context': typeof ContextRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/outputs': typeof OutputsRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/scheduled': typeof ScheduledRoute
  '/signup': typeof SignupRoute
  '/workspaces': typeof WorkspacesRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/gatekeepers_/$appId': typeof GatekeepersAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/scheduled'
    | '/signup'
    | '/workspaces'
    | '/blueprint/$id'
    | '/chat/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/scheduled'
    | '/signup'
    | '/workspaces'
    | '/blueprint/$id'
    | '/chat/$id'
    | '/gadget/$id'
    | '/gatekeepers/$appId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blueprints'
    | '/context'
    | '/explore'
    | '/gatekeepers'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/scheduled'
    | '/signup'
    | '/workspaces'
    | '/blueprint/$id'
    | '/chat/$id'
    | '/gadget/$id'
    | '/gatekeepers_/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlueprintsRoute: typeof BlueprintsRoute
  ContextRoute: typeof ContextRoute
  ExploreRoute: typeof ExploreRoute
  GatekeepersRoute: typeof GatekeepersRoute
  OutputsRoute: typeof OutputsRoute
  ProfileRoute: typeof ProfileRoute
  ProvidersRoute: typeof ProvidersRoute
  ScheduledRoute: typeof ScheduledRoute
  SignupRoute: typeof SignupRoute
  WorkspacesRoute: typeof WorkspacesRoute
  BlueprintIdRoute: typeof BlueprintIdRoute
  ChatIdRoute: typeof ChatIdRoute
  GadgetIdRoute: typeof GadgetIdRoute
  GatekeepersAppIdRoute: typeof GatekeepersAppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs': {
      id: '/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof OutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers': {
      id: '/gatekeepers'
      path: '/gatekeepers'
      fullPath: '/gatekeepers'
      preLoaderRoute: typeof GatekeepersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers_/$appId': {
      id: '/gatekeepers_/$appId'
      path: '/gatekeepers/$appId'
      fullPath: '/gatekeepers/$appId'
      preLoaderRoute: typeof GatekeepersAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gadget/$id': {
      id: '/gadget/$id'
      path: '/gadget/$id'
      fullPath: '/gadget/$id'
      preLoaderRoute: typeof GadgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint/$id': {
      id: '/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/blueprint/$id'
      preLoaderRoute: typeof BlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlueprintsRoute: BlueprintsRoute,
  ContextRoute: ContextRoute,
  ExploreRoute: ExploreRoute,
  GatekeepersRoute: GatekeepersRoute,
  OutputsRoute: OutputsRoute,
  ProfileRoute: ProfileRoute,
  ProvidersRoute: ProvidersRoute,
  ScheduledRoute: ScheduledRoute,
  SignupRoute: SignupRoute,
  WorkspacesRoute: WorkspacesRoute,
  BlueprintIdRoute: BlueprintIdRoute,
  ChatIdRoute: ChatIdRoute,
  GadgetIdRoute: GadgetIdRoute,
  GatekeepersAppIdRoute: GatekeepersAppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
