/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GatekeepersRouteImport } from './routes/gatekeepers'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GadgetIdRouteImport } from './routes/gadget.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as BlueprintIdRouteImport } from './routes/blueprint.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GatekeepersRoute = GatekeepersRouteImport.update({
  id: '/gatekeepers',
  path: '/gatekeepers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GadgetIdRoute = GadgetIdRouteImport.update({
  id: '/gadget/$id',
  path: '/gadget/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintIdRoute = BlueprintIdRouteImport.update({
  id: '/blueprint/$id',
  path: '/blueprint/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/gadget/$id': typeof GadgetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/gadget/$id': typeof GadgetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/gatekeepers': typeof GatekeepersRoute
  '/profile': typeof ProfileRoute
  '/providers': typeof ProvidersRoute
  '/signup': typeof SignupRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/gadget/$id': typeof GadgetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/gatekeepers'
    | '/profile'
    | '/providers'
    | '/signup'
    | '/blueprint/$id'
    | '/chat/$id'
    | '/gadget/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/gatekeepers'
    | '/profile'
    | '/providers'
    | '/signup'
    | '/blueprint/$id'
    | '/chat/$id'
    | '/gadget/$id'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/gatekeepers'
    | '/profile'
    | '/providers'
    | '/signup'
    | '/blueprint/$id'
    | '/chat/$id'
    | '/gadget/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  GatekeepersRoute: typeof GatekeepersRoute
  ProfileRoute: typeof ProfileRoute
  ProvidersRoute: typeof ProvidersRoute
  SignupRoute: typeof SignupRoute
  BlueprintIdRoute: typeof BlueprintIdRoute
  ChatIdRoute: typeof ChatIdRoute
  GadgetIdRoute: typeof GadgetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatekeepers': {
      id: '/gatekeepers'
      path: '/gatekeepers'
      fullPath: '/gatekeepers'
      preLoaderRoute: typeof GatekeepersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gadget/$id': {
      id: '/gadget/$id'
      path: '/gadget/$id'
      fullPath: '/gadget/$id'
      preLoaderRoute: typeof GadgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint/$id': {
      id: '/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/blueprint/$id'
      preLoaderRoute: typeof BlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  GatekeepersRoute: GatekeepersRoute,
  ProfileRoute: ProfileRoute,
  ProvidersRoute: ProvidersRoute,
  SignupRoute: SignupRoute,
  BlueprintIdRoute: BlueprintIdRoute,
  ChatIdRoute: ChatIdRoute,
  GadgetIdRoute: GadgetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
