// Build the Context Library SPA into committed single-file HTML for startAppUi().

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const pkgDir = resolve(fileURLToPath(import.meta.url), "..");
const outFile = join(pkgDir, "src", "generated", "app.txt");

console.log("building context library app single-file bundle…");
execFileSync(
  "pnpm",
  ["exec", "vite", "build", "-c", "vite.config.ts"],
  { cwd: pkgDir, stdio: "inherit" },
);

// Vite preserves app/index.html under outDir.
const built = join(pkgDir, "dist-app", "app", "index.html");
const html = readFileSync(built, "utf8");

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `<!-- Generated by build-app.mjs from packages/gatekeeper-context/app. Do not edit. -->\n` +
  html,
);
console.log(`wrote ${outFile} (${(html.length / 1024).toFixed(0)} KiB)`);
